export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const GET_DETAILS_PRODUCT="GET_DETAILS_PRODUCT";
export const ADD_TO_CART="ADD_TO_CART";