export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const GET_DETAILS_PRODUCT="GET_DETAILS_PRODUCT";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const CLEAR_CART="CLEAR_CART";
export const INCRESAMOUNT="INCRESAMOUNT";
export const DICRESAMOUNT="DICRESAMOUNT";
export const AMOUNT_PRODUCT="DICRESAMOUNT";
export const LOGIN="LOGIN";
export const LOGOUT="LOGOUT";
export const CHECK_LOGIN_USER="CHECKLOGINUSER";
export const LOGIN_WITH_GOOGLE="LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_FACEBOOK="LOGIN_WITH_FACEBOOK";
export const CREAET_USER_ACOUNT="LOGIN_WITH_FACEBOOK";
export const RESET_PASSWORD="RESET_PASSWORD";
export const ADD_FAVORITE="ADD_FAVORITE";
export const REMOVE_FAVORITE="REMOVE_FAVORITE";
export const FILTER_SEARCH="FILTER_SEARCH";
export const CATEGORIE="CATEGORIE";
export const FILTER_CATEGORIE="FILTER_CATEGORIE";
export const INPUT_TEXT ="FILTRED_Text";
export const RATE_PRODUCT="RATE_PRODUCT";
export const LIST_USERS ="LIST_USERS";
export const GET_ALL_POSTS="GET_ALL_POSTS";
export const GET_POST="GET_POST";
export const SEARCH_POST="SEARCH_POST";
export const RECENT_POST="RECENT_POST";
export const GET_TEAM="GET_TEAM";
export const SENTMESSAGE="SENTMESSAGE";








